"""OUCH 4.2 Enter Order ('O') message, 49 bytes, big endian integers."""
from __future__ import annotations

import struct

ENTER_ORDER = struct.Struct(">c14scI8sII4scccIcc")
assert ENTER_ORDER.size == 49

TIF_IOC = 0


def token_for(n: int) -> bytes:
    """Order token as generated by rtl/ouch_tx.v: 'TT' + 12 upper-case hex digits."""
    return b"TT" + f"{n & 0xFFFFFFFFFFFF:012X}".encode()


def encode_enter_order(token: bytes, side: str, shares: int, stock: bytes | str, price: int,
                       tif: int = TIF_IOC, firm: bytes | str = b"TTRD", display: bytes = b"Y",
                       capacity: bytes = b"P", iso: bytes = b"N", min_qty: int = 0,
                       cross_type: bytes = b"N", customer_type: bytes = b"N") -> bytes:
    if isinstance(stock, str):
        stock = stock.encode("ascii")
    if isinstance(firm, str):
        firm = firm.encode("ascii")
    return ENTER_ORDER.pack(b"O", token.ljust(14, b" "), side.encode(), shares,
                            stock.ljust(8, b" "), price, tif, firm.ljust(4, b" "),
                            display, capacity, iso, min_qty, cross_type, customer_type)


def decode_enter_order(b: bytes) -> dict:
    (t, token, side, shares, stock, price, tif, firm, display, capacity, iso, min_qty,
     cross, cust) = ENTER_ORDER.unpack(b)
    return {"type": t.decode(), "token": token.decode(), "side": side.decode(),
            "shares": shares, "stock": stock.decode(), "price": price, "tif": tif,
            "firm": firm.decode(), "display": display.decode(), "capacity": capacity.decode(),
            "iso": iso.decode(), "min_qty": min_qty, "cross_type": cross.decode(),
            "customer_type": cust.decode()}
